"""init github signals

Revision ID: cdcc68ff9f93
Revises:
Create Date: 2026-01-13 19:25:01.942096

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cdcc68ff9f93"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_commits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repo_owner", sa.String(length=200), nullable=False),
        sa.Column("repo_name", sa.String(length=200), nullable=False),
        sa.Column("sha", sa.String(length=60), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("author_login", sa.String(length=200), nullable=True),
        sa.Column("committed_at_gh", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "repo_owner", "repo_name", "sha", name="uq_commit_repo_sha"
        ),
    )
    op.create_table(
        "github_issues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repo_owner", sa.String(length=200), nullable=False),
        sa.Column("repo_name", sa.String(length=200), nullable=False),
        sa.Column("gh_id", sa.BigInteger(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=50), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("created_at_gh", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at_gh", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at_gh", sa.DateTime(timezone=True), nullable=True),
        sa.Column("author_login", sa.String(length=200), nullable=True),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "repo_owner", "repo_name", "gh_id", name="uq_issue_repo_ghid"
        ),
    )
    op.create_table(
        "github_pull_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repo_owner", sa.String(length=200), nullable=False),
        sa.Column("repo_name", sa.String(length=200), nullable=False),
        sa.Column("gh_id", sa.BigInteger(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("created_at_gh", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at_gh", sa.DateTime(timezone=True), nullable=False),
        sa.Column("merged_at_gh", sa.DateTime(timezone=True), nullable=True),
        sa.Column("author_login", sa.String(length=200), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repo_owner", "repo_name", "gh_id", name="uq_pr_repo_ghid"),
    )
    op.create_table(
        "github_repos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner", "name", name="uq_github_repo_owner_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("github_repos")
    op.drop_table("github_pull_requests")
    op.drop_table("github_issues")
    op.drop_table("github_commits")
    # ### end Alembic commands ###
